name: hackernews

description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  firebase: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  html: ^0.15.0
  http: ^0.13.3
  json_annotation: ^4.4.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.2.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  lints: ^1.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/
  fonts:
    - family: FiraCode
      fonts:
        - asset: fonts/FiraCode-Bold.ttf
          weight: 700
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
          weight: 400
